/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'on-primary-container': '#007117',
        outline: '#84967e',
        'on-tertiary': '#2d3137',
        'on-primary-fixed-variant': '#00530e',
        'primary-fixed-dim': '#00e639',
        'primary-container': '#00ff41',
        'on-error': '#690005',
        secondary: '#ffd393',
        primary: '#ebffe2',
        'surface-container-high': '#222b33',
        'tertiary-container': '#d9dce5',
        'tertiary-fixed': '#dfe2eb',
        'surface-bright': '#313a43',
        'on-error-container': '#ffdad6',
        'on-background': '#dae3ee',
        'on-secondary-fixed-variant': '#614000',
        'on-surface': '#dae3ee',
        background: '#0b141c',
        'secondary-fixed': '#ffddaf',
        'on-surface-variant': '#b9ccb2',
        'surface-dim': '#0b141c',
        'secondary-fixed-dim': '#ffba43',
        tertiary: '#f8f8ff',
        'on-primary-fixed': '#002203',
        'on-secondary': '#432c00',
        'tertiary-fixed-dim': '#c3c6cf',
        'surface-container-highest': '#2d363e',
        'surface-variant': '#2d363e',
        'surface-container': '#182028',
        'surface-tint': '#00e639',
        surface: '#0b141c',
        'on-tertiary-container': '#5d6168',
        'error-container': '#93000a',
        'on-secondary-fixed': '#281800',
        'surface-container-low': '#141c24',
        error: '#ffb4ab',
        'on-primary': '#003907',
        'secondary-container': '#fdaf00',
        'inverse-on-surface': '#29313a',
        'on-tertiary-fixed': '#181c22',
        'on-secondary-container': '#694600',
        'on-tertiary-fixed-variant': '#43474e',
        'primary-fixed': '#72ff70',
        'outline-variant': '#3b4b37',
        'inverse-surface': '#dae3ee',
        'inverse-primary': '#006e16',
        'surface-container-lowest': '#060f16',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'margin-desktop': '64px',
        gutter: '24px',
        'grid-size': '32px',
        'margin-mobile': '16px',
        unit: '4px',
      },
      fontFamily: {
        'label-caps': ['JetBrains Mono', 'monospace'],
        'body-lg': ['JetBrains Mono', 'monospace'],
        'headline-lg': ['Space Grotesk', 'sans-serif'],
        'headline-lg-mobile': ['Space Grotesk', 'sans-serif'],
        'code-sm': ['JetBrains Mono', 'monospace'],
        'body-md': ['JetBrains Mono', 'monospace'],
        'headline-md': ['Space Grotesk', 'sans-serif'],
      },
      fontSize: {
        'label-caps': ['12px', { lineHeight: '1', letterSpacing: '0.1em', fontWeight: '700' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'headline-lg': ['48px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg-mobile': ['32px', { lineHeight: '1.2', fontWeight: '700' }],
        'code-sm': ['12px', { lineHeight: '1.4', fontWeight: '400' }],
        'body-md': ['14px', { lineHeight: '1.6', fontWeight: '400' }],
        'headline-md': ['24px', { lineHeight: '1.3', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
}
